import os

ROOT_PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

DATAFILE_PATH = os.path.join(ROOT_PROJECT_PATH, "data", "recipeData.csv")
EXCLUDED_COLUMNS = ["BeerID", "UserId", "Name", "URL"]


BEER_STYLE_MAP = {
    "Cream Ale": "Ale",
    "Holiday/Winter Special Spiced Beer": "Spiced/Seasonal",
    "American IPA": "Pale Ale",
    "Belgian Blond Ale": "Belgian",
    "American Pale Ale": "Pale Ale",
    "Imperial IPA": "Pale Ale",
    "Robust Porter": "Porter & Stout",
    "Bohemian Pilsener": "Lager",
    "Saison": "Belgian",
    "Northern English Brown": "Ale",
    "English IPA": "Pale Ale",
    "Traditional Bock": "Bock",
    "Premium American Lager": "Lager",
    "Belgian Golden Strong Ale": "Belgian",
    "Double IPA": "Pale Ale",
    "Blonde Ale": "Pale Ale",
    "Light American Lager": "Lager",
    "German Pilsner (Pils)": "Lager",
    "American Brown Ale": "Ale",
    "Oatmeal Stout": "Porter & Stout",
    "Specialty Beer": "Specialty",
    "American Amber Ale": "Ale",
    "Kölsch": "Hybrid Ale",
    "Witbier": "Wheat Beer",
    "Weizen/Weissbier": "Wheat Beer",
    "Trappist Single": "Belgian",
    "Russian Imperial Stout": "Porter & Stout",
    "Specialty IPA: Black IPA": "Pale Ale",
    "Sweet Stout": "Porter & Stout",
    "Strong Scotch Ale": "Scotch Ale",
    "Belgian Tripel": "Belgian",
    "American Stout": "Porter & Stout",
    "Belgian Pale Ale": "Belgian",
    "Dark American Lager": "Lager",
    "Dry Stout": "Porter & Stout",
    "Belgian Dark Strong Ale": "Belgian",
    "American Wheat or Rye Beer": "Wheat Beer",
    "Vienna Lager": "Lager",
    "Special/Best/Premium Bitter": "Bitter",
    "Experimental Beer": "Specialty",
    "Irish Red Ale": "Ale",
    "Old Ale": "Strong Ale",
    "Extra Special/Strong Bitter (ESB)": "Bitter",
    "Winter Seasonal Beer": "Spiced/Seasonal",
    "Standard American Lager": "Lager",
    "Wood-Aged Beer": "Specialty",
    "Fruit Beer": "Fruit/Spiced",
    "British Golden Ale": "Pale Ale",
    "Flanders Red Ale": "Sour Ale",
    "Berliner Weisse": "Sour Ale",
    "Oktoberfest/Märzen": "Lager",
    "Munich Helles": "Lager",
    "Classic American Pilsner": "Lager",
    "Gueuze": "Sour Ale",
    "Brown Porter": "Porter & Stout",
    "American Light Lager": "Lager",
    "English Cider": "Cider/Perry",
    "Fruit Cider": "Cider/Perry",
    "Altbier": "Hybrid Ale",
    "Spice  Herb  or Vegetable Beer": "Fruit/Spiced",
    "Southern English Brown": "Ale",
    "Other Smoked Beer": "Smoked",
    "Belgian Dubbel": "Belgian",
    "Cyser (Apple Melomel)": "Mead",
    "Metheglin": "Mead",
    "Specialty IPA: Red IPA": "Pale Ale",
    "Belgian Specialty Ale": "Belgian",
    "Foreign Extra Stout": "Porter & Stout",
    "Braggot": "Mead",
    "Weizenbock": "Wheat Beer",
    "International Pale Lager": "Lager",
    "Common Cider": "Cider/Perry",
    "Imperial Stout": "Porter & Stout",
    "Strong Bitter": "Bitter",
    "Dusseldorf Altbier": "Hybrid Ale",
    "Bière de Garde": "Belgian",
    "Dunkelweizen": "Wheat Beer",
    "Schwarzbier": "Lager",
    "Baltic Porter": "Porter & Stout",
    "Doppelbock": "Bock",
    "American Barleywine": "Barleywine",
    "Other Specialty Cider or Perry": "Cider/Perry",
    "Specialty IPA: White IPA": "Pale Ale",
    "Mild": "Mild Ale",
    "California Common Beer": "Hybrid Lager",
    "American Wheat Beer": "Wheat Beer",
    "British Strong Ale": "Strong Ale",
    "Other Fruit Melomel": "Mead",
    "Classic Rauchbier": "Smoked",
    "Märzen": "Lager",
    "American Lager": "Lager",
    "Wee Heavy": "Scotch Ale",
    "Dry Mead": "Mead",
    "British Brown Ale": "Ale",
    "Weissbier": "Wheat Beer",
    "Clone Beer": "Specialty",
    "Best Bitter": "Bitter",
    "Standard/Ordinary Bitter": "Bitter",
    "Czech Premium Pale Lager": "Lager",
    "Mixed-Fermentation Sour Beer": "Sour Ale",
    "Scottish Heavy 70/-": "Scotch Ale",
    "English Porter": "Porter & Stout",
    "Czech Dark Lager": "Lager",
    "Roggenbier (German Rye Beer)": "Wheat Beer",
    "Gose": "Sour Ale",
    "Fruit Lambic": "Sour Ale",
    "Sweet Mead": "Mead",
    "Australian Sparkling Ale": "Hybrid Ale",
    "Maibock/Helles Bock": "Bock",
    "American Strong Ale": "Strong Ale",
    "Specialty IPA: Belgian IPA": "Pale Ale",
    "Mixed-Style Beer": "Specialty",
    "North German Altbier": "Hybrid Ale",
    "American Porter": "Porter & Stout",
    "Dortmunder Export": "Lager",
    "German Pils": "Lager",
    "Irish Stout": "Porter & Stout",
    "English Barleywine": "Barleywine",
    "Specialty IPA: Rye IPA": "Pale Ale",
    "Scottish Export": "Scotch Ale",
    "Scottish Export 80/-": "Scotch Ale",
    "Tropical Stout": "Porter & Stout",
    "Eisbock": "Bock",
    "Semi-Sweet Mead": "Mead",
    "French Cider": "Cider/Perry",
    "Munich Dunkel": "Lager",
    "Specialty Smoked Beer": "Smoked",
    "Open Category Mead": "Mead",
    "Wild Specialty Beer": "Specialty",
    "Apple Wine": "Mead",
    "Czech Pale Lager": "Lager",
    "California Common": "Hybrid Lager",
    "Flanders Brown Ale/Oud Bruin": "Sour Ale",
    "International Amber Lager": "Lager",
    "Alternative Grain Beer": "Specialty",
    "Scottish Light 60/-": "Scotch Ale",
    "Helles Bock": "Bock",
    "Lambic": "Sour Ale",
    "Pre-Prohibition Lager": "Lager",
    "Ordinary Bitter": "Bitter",
    "Wheatwine": "Barleywine",
    "Dunkles Weissbier": "Wheat Beer",
    "Straight (Unblended) Lambic": "Sour Ale",
    "Kentucky Common": "Hybrid Ale",
    "New England Cider": "Cider/Perry",
    "Pyment (Grape Melomel)": "Mead",
    "Lichtenhainer": "Smoked",
    "Irish Extra Stout": "Porter & Stout",
    "Rauchbier": "Smoked",
    "Specialty IPA: Brown IPA": "Pale Ale",
    "Kellerbier: Amber Kellerbier": "Lager",
    "Sahti": "Specialty",
    "Oud Bruin": "Sour Ale",
    "Piwo Grodziskie": "Smoked",
    "Specialty Fruit Beer": "Fruit/Spiced",
    "Alternative Sugar Beer": "Specialty",
    "Kellerbier: Pale Kellerbier": "Lager",
    "Classic Style Smoked Beer": "Smoked",
    "Czech Amber Lager": "Lager",
    "Scottish Heavy": "Scotch Ale",
    "Traditional Perry": "Cider/Perry",
    "Festbier": "Lager",
    "Brett Beer": "Sour Ale",
    "Dark Mild": "Mild Ale",
    "London Brown Ale": "Ale",
    "Fruit and Spice Beer": "Fruit/Spiced",
    "German Helles Exportbier": "Lager",
    "Autumn Seasonal Beer": "Spiced/Seasonal",
    "International Dark Lager": "Lager",
    "Roggenbier": "Wheat Beer",
    "Dunkles Bock": "Bock",
    "German Leichtbier": "Lager",
    "Scottish Light": "Scotch Ale",
    "Pre-Prohibition Porter": "Porter & Stout",
    "Specialty Wood-Aged Beer": "Specialty",
}
